// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package namespaced

import (
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/accessapproval"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/accesscontextmanager"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/apigee"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/beyondcorp"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/bigquery"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/bigtable"
	composer "github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudcomposer"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudfunctions"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudplatform"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudrun"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudscheduler"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/cloudtasks"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/compute"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/container"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/containerattached"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/containeraws"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/containerazure"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/dataflow"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/dataplex"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/dataproc"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/datastream"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/developerconnect"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/dns"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/endpoints"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/firebaserules"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/gameservices"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/gkehub"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/healthcare"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/iap"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/identityplatform"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/kms"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/logging"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/modelarmor"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/monitoring"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/networksecurity"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/notebooks"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/oslogin"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/privateca"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/project"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/pubsub"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/redis"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/secretmanager"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/servicenetworking"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/sourcerepo"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/spanner"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/sql"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/storage"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/storagetransfer"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/tags"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/tpu"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/vertexai"
	"github.com/aayushrangwala/provider-upjet-gcp/v2/config/namespaced/vpcaccess"
)

func init() {
	ProviderConfiguration.AddConfig(accessapproval.Configure)
	ProviderConfiguration.AddConfig(accesscontextmanager.Configure)
	ProviderConfiguration.AddConfig(apigee.Configure)
	ProviderConfiguration.AddConfig(bigtable.Configure)
	ProviderConfiguration.AddConfig(composer.Configure)
	ProviderConfiguration.AddConfig(cloudfunctions.Configure)
	ProviderConfiguration.AddConfig(cloudplatform.Configure)
	ProviderConfiguration.AddConfig(cloudrun.Configure)
	ProviderConfiguration.AddConfig(cloudscheduler.Configure)
	ProviderConfiguration.AddConfig(cloudtasks.Configure)
	ProviderConfiguration.AddConfig(containerattached.Configure)
	ProviderConfiguration.AddConfig(containeraws.Configure)
	ProviderConfiguration.AddConfig(containerazure.Configure)
	ProviderConfiguration.AddConfig(compute.Configure)
	ProviderConfiguration.AddConfig(container.Configure)
	ProviderConfiguration.AddConfig(dataflow.Configure)
	ProviderConfiguration.AddConfig(dataplex.Configure)
	ProviderConfiguration.AddConfig(dataproc.Configure)
	ProviderConfiguration.AddConfig(datastream.Configure)
	ProviderConfiguration.AddConfig(developerconnect.Configure)
	ProviderConfiguration.AddConfig(dns.Configure)
	ProviderConfiguration.AddConfig(endpoints.Configure)
	ProviderConfiguration.AddConfig(firebaserules.Configure)
	ProviderConfiguration.AddConfig(gameservices.Configure)
	ProviderConfiguration.AddConfig(iap.Configure)
	ProviderConfiguration.AddConfig(identityplatform.Configure)
	ProviderConfiguration.AddConfig(logging.Configure)
	ProviderConfiguration.AddConfig(kms.Configure)
	ProviderConfiguration.AddConfig(networksecurity.Configure)
	ProviderConfiguration.AddConfig(notebooks.Configure)
	ProviderConfiguration.AddConfig(privateca.Configure)
	ProviderConfiguration.AddConfig(oslogin.Configure)
	ProviderConfiguration.AddConfig(project.Configure)
	ProviderConfiguration.AddConfig(pubsub.Configure)
	ProviderConfiguration.AddConfig(redis.Configure)
	ProviderConfiguration.AddConfig(secretmanager.Configure)
	ProviderConfiguration.AddConfig(servicenetworking.Configure)
	ProviderConfiguration.AddConfig(sourcerepo.Configure)
	ProviderConfiguration.AddConfig(spanner.Configure)
	ProviderConfiguration.AddConfig(storage.Configure)
	ProviderConfiguration.AddConfig(storagetransfer.Configure)
	ProviderConfiguration.AddConfig(sql.Configure)
	ProviderConfiguration.AddConfig(redis.Configure)
	ProviderConfiguration.AddConfig(bigquery.Configure)
	ProviderConfiguration.AddConfig(beyondcorp.Configure)
	ProviderConfiguration.AddConfig(vertexai.Configure)
	ProviderConfiguration.AddConfig(tags.Configure)
	ProviderConfiguration.AddConfig(tpu.Configure)
	ProviderConfiguration.AddConfig(vpcaccess.Configure)
	ProviderConfiguration.AddConfig(healthcare.Configure)
	ProviderConfiguration.AddConfig(gkehub.Configure)
	ProviderConfiguration.AddConfig(modelarmor.Configure)
	ProviderConfiguration.AddConfig(monitoring.Configure)
}
